### PR TITLE
Module tests test file

### PR DESCRIPTION
**Pull request by agudek**
Fixed the d3 not defined errors for module tests. Added test files for graph1 and all-prs-force-layout.

### CODE REVIEW

**Comment by DaanvanderValk** [comment]
Very nice! There are merge conflicts though, probably concerning the library references.

**Comment by agudek** [comment]
@DaanvanderValk Fixed!

**Comment by borek2** [comment]
whoooo more coverage :)!

**Comment by borek2** [comment]
Btw, shouldnt the test files be in the spec folder?

**Comment by agudek** [comment]
@borek2 They are. The file in the test folder is the configuration file for karma with requirejs.

**Pull request merged**
