### PR TITLE
Force layout visualisation

### PR DESCRIPTION
**Pull request by agudek**
Added new visualisation with force layout.

Also changed module size definition a little to be able to draw visualisation in full width

### CODE REVIEW

**Comment by mboom** [comment]
This is a very nice graph!. Source code seems to be good. Also noticed that the unused field size is removed from the graph. Good job!

**Comment by DaanvanderValk** [comment]
Looks very nice for the demo, although an attentive observer may notice that Ahmet's account is referred to with Borek's picture.

**Comment by DaanvanderValk** [comment]
Was any documentation written about this graph? If not, obviously it should be.

**Comment by agudek** [comment]
@DaanvanderValk The graph shows the pull requests reviewed by the user. These could very well be in repositories other than his own, so it is entirely possible that no repo of the user is shown in this graph.

For the documentation, I will add it to the file on drive ASAP.

**Pull request merged**
