### PR TITLE
Reviews on my prs module

### PR DESCRIPTION
**Pull request by agudek**
Created new visualisation on dashboard showing other people revieving your PRs + test. 
It is now also possible to create custom sized SVGs.

### CODE REVIEW

**Comment by DaanvanderValk** [comment]
Looks totally awesome, great work! Nevertheless, I have some comments.
About the top right module:
- The title could be nicer, perhaps "Reviews on your pull requests"? When abbreviating pull requests is needed because of the lay-out, I would use "PRs".
- I think it looks better when the arrows for scrolling through reviewers are completely invisible when there's five or less of them. The way they're showed when there is more then five (row 2) is great.

**Comment by DaanvanderValk** [comment]
By the way, the message from coveralls above should be ignored - after adding the tests, there is a 2% coverage increase to 43% overall.

**Comment by lvdoorn** [comment]
Looks great! Some suggestions: maybe we can show the time that a reviewer spent on your pull request and if they commented on it. Also, although not really related to this particular PR, I think we should round off the minutes in the average peer review duration module.

**Comment by agudek** [comment]
@DaanvanderValk Implemented the suggestions from your first comment. The second set of suggestions will be addressed in the next sprint.

**Pull request merged**
