### PR TITLE
Reviews oyprs aggregator

### PR DESCRIPTION
**Pull request by borek2**
Added real data to peer reviewers summary with avatars

### CODE REVIEW

**Comment by borek2** [comment]
Eh d3 is not defined Travis says... Does someone know what to do? You can edit my Pr , its basically done.

**Comment by agudek** [comment]
@borek2 You have to re-run travis. There are some asynchronity issues due to the use of require.

**Comment by DaanvanderValk** [comment]
Code and functionality seems nice, is there a username I could enter to see actual results? Because our default user Travis doesn't seem to have reviewed pull requests.

**Comment by borek2** [comment]
Travis does (you can scroll down on the module) @DaanvanderValk . But there are some problems which i tried to fix in #238 . So that one is high prio.

**Pull request merged**
