### PR TITLE
Converted to correct graph format

### PR DESCRIPTION
**Pull request by borek2**
I have converted the data to the requested format for easier implementation in the graphs

@mboom

### CODE REVIEW

**Comment by mboom** [comment]
Thank you, this is the daeta-format I wanted.

**Comment by borek2** [comment]
daeta-format

**Comment by mboom** [comment]
*data

**Comment by DaanvanderValk** [comment]
When a pull request page is closed in the browser, this is the end of the (semantic) session. Maybe we want to implemented a function to group some sessions together. For example, when I close a pull request page and reopen it in the next 15 minutes, I would consider this the same session.

**Comment by borek2** [comment]
I wouldnt say 15 minutes, but i understand what you are saying. Still i don't think that is a high priority for now. Maybe if we see a lot of "small" sessions within the graphs it is something to look into, but for now i think it is ok like this.

**Pull request merged**
