### PR TITLE
sig feedback 0 added

### PR DESCRIPTION
**Pull request by mboom**

### CODE REVIEW

**Comment by DaanvanderValk** [comment]
Can I find the original document/webpage somewhere? The feedback PDF contains some hidden text because of the scroll bars.

**Comment by DaanvanderValk** [comment]
@breijm: is there a way to exclude the libraries from SIG? Most of their refactoring candidates contain JQuery and the other libraries; I guess refactoring their code wouldn't really be useful.

**Comment by mboom** [comment]
@DaanvanderValk As far as I know, that is not possible. You can request specific information. Please see Slack for more information about this issue.

**Comment by breijm** [comment]
@DaanvanderValk I think it's possible though I have no personal experience with this tool. I was told that it is possible to exclude files from the scan and that the instructions can be found when you open the tool. I would ask around on Slack and see if other teams managed to do this.

**Pull request merged**
