### PR TITLE
D3 tip

### PR DESCRIPTION
**Pull request by agudek**
Think I got it this time :smile: hopefully we won't receive any d3 or d3.tip not defined errors anymore.

Also improved the tooltips in all-prs-force-layout and started on a tooltip functionality in graph1.

Finally, also made all <a> tags open links in new tabs.

### CODE REVIEW

**Comment by DaanvanderValk** [comment]
When trying `grunt karma` with these changes (commit 345151c) locally, I consistently get the following error:
```
Uncaught TypeError: d3.tip is not a function
  at C:/Users/Daan/contextproject/TI2806/src/modules/all-prs-force-layout.js:9
```

Can anyone reproduce this?

**Comment by lvdoorn** [comment]
I also get this error, very strange considering the travis build passes.

**Comment by agudek** [comment]
@DaanvanderValk @lvdoorn - grunt karma fails for me too, but grunt seems to work consistently. Have no idea why.

**Comment by mboom** [comment]
The code seems to be good, nice that there is a small test coverage improvement 👍 .

**Comment by agudek** [comment]
@DaanvanderValk @lvdoorn @mboom Fixed it now for sure :smile:

**Comment by lvdoorn** [comment]
If it works, it works.

**Pull request merged**
